package org.jawata.mcp.tools.refactoring;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.jawata.mcp.fixtures.TestProjectHelper;
import org.jawata.mcp.tools.DataTool;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Sprint 28d-rescue row 10 — Encapsulate Record: the REGRESSION LOCK.
 *
 * <p>Read {@link RowParity}'s javadoc for what a golden proves here and what it does not.</p>
 *
 * <p><b>What the golden is uniquely good for here is the ACCESSOR TEXT and the SECOND
 * FILE.</b> The row's output is generated by JDT's self-encapsulate engine rather than
 * written here, so what it emits — the visibility, the javadoc, the body, the order the
 * members land in — is not something a substring assertion states. Pinning both files whole
 * is what would catch the engine changing its mind under a target-platform bump, and the
 * second file is where the rewriting that matters happened: the reads nobody pointed the tool
 * at.</p>
 *
 * <p>Refresh with {@code -Djawata.test.parity.record=true}.</p>
 */
class EncapsulateRecordParityTest {

    @RegisterExtension
    TestProjectHelper helper = new TestProjectHelper();

    @Test
    @DisplayName("row 10 pins both accessors, the skipped constant, and the other file's reads")
    void theRowsOutcomeIsPinned() throws Exception {
        RowParity.appliedRow(helper, "data", "encapsulate_record",
            (service, cache) -> new DataTool(() -> service, cache),
            pkg -> {
                ObjectNode args = new ObjectMapper().createObjectNode();
                args.put("kind", "encapsulate_record");
                Path file = pkg.resolve("EncapsulateRecordTargets.java");
                args.put("filePath", file.toString());
                try {
                    String[] lines = Files.readString(file, StandardCharsets.UTF_8)
                        .split("\n", -1);
                    for (int i = 0; i < lines.length; i++) {
                        if (lines[i].contains("public static class Coordinate")) {
                            args.put("line", i);
                            args.put("column", lines[i].indexOf("Coordinate"));
                            return args;
                        }
                    }
                    throw new AssertionError("PROOF OF LIFE: the fixture no longer declares"
                        + " Coordinate");
                } catch (Exception e) {
                    throw new IllegalStateException(e);
                }
            },
            List.of("EncapsulateRecordTargets.java", "EncapsulateRecordUser.java"));
    }
}
