package org.jawata.mcp.tools.refactoring;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * WHICH STAGE 6 ROWS HAVE BEEN DEMONSTRATED ON CODE WE DID NOT AUTHOR, and which have not.
 *
 * <p>The per-row contract asks for a fork-corpus demonstration per row. <b>Eleven of the
 * twelve have one</b>; row 38 has a measured reason instead, in
 * {@link NotificationForkSliceTest}. A C6 audit found eleven absent AND unexplained, and
 * was right that those two states read identically from outside — Stage 3 wrote its reasons
 * down, Stage 6 had not.</p>
 *
 * <p>This file is the written state, and it is a TEST rather than a comment so it cannot
 * quietly stop being true. It fails when the count changes in either direction: build a
 * slice and this goes red until the list is updated, delete one and the same. A note in a
 * markdown file would have done neither.</p>
 *
 * <h2>The one that is not built, and why that is a measurement</h2>
 *
 * <p>Row 38 (Remove Subclass) needs a CONCRETE class extending a CONCRETE class and
 * overriding nothing. {@code find_quality_issue(kind=composition_over_inheritance)} over all
 * 1336 main files returns NINE findings, SEVEN of which override none of their inherited
 * members — and SIX of those seven fail a DIFFERENT precondition each (abstract with
 * subtypes; does override after all; four generic parents, three of them self-referential,
 * whose constructors pass method references rather than forwarding). The seventh,
 * {@code RegisterWorker}, fits structurally and is blocked because
 * its parent's only constructor is generated by Lombok, which JDT does not run.
 * {@link NotificationForkSliceTest} pins that refusal, so if the population ever changes
 * this stops being true out loud rather than quietly.</p>
 *
 * <p>This is the same shape as Stage 3's declared deviation, recorded in
 * {@link ForkShapeCensusTest}: the row is not unbuilt, it is unbuildable HERE, and the
 * difference is the measurement.</p>
 *
 * <h2>What the demonstrations bought, which is the argument for having built them</h2>
 *
 * <p>Row 36's slice broke that row three times before it passed, and every one was a shape
 * the hand-written fixture could not have contained: a receiver written two ways in one
 * class, a class forwarding to two fields refused outright, and — the sharpest — the
 * forwarder's own name emitted where the DELEGATE's name belonged, which the fixture hid
 * because both names were the same word. That row had already passed its unit tests, its
 * parity golden and two reviews.</p>
 *
 * <p>The second pass found five more, in rows that had also already passed everything:
 * a {@code final} field built in a constructor refused as though it had a lifecycle; a
 * same-name forwarder refused as a collision when it was the very method being inlined; a
 * dangling {@code @link} to the deleted class that no compile gate can see; and — the one
 * no fixture could have reached — {@link org.jawata.mcp.tools.MoveStatementsToCallersTool}'s
 * same-file caller path, which had never run at all, because a caller in the file being
 * edited is the one arrangement every fixture happened not to have.</p>
 */
class Stage6ForkDemonstrationStatusTest {

    private static final String TESTS =
        "org.jawata.mcp.tests/src/org/jawata/mcp/tools/refactoring";

    /** Row → the fork slice that demonstrates it, or null while it has none. */
    private static final Map<String, String> ROWS = new java.util.LinkedHashMap<>(Map.ofEntries(
        Map.entry("36 Remove Middle Man", "RemoveMiddleManForkSliceTest.java"),
        Map.entry("23 Move Field", "NotificationForkSliceTest.java"),
        Map.entry("17 Inline Class", "InterceptingFilterForkSliceTest.java"),
        Map.entry("38 Remove Subclass", ""),
        Map.entry("24 Move Function (static)", "MapReduceForkSliceTest.java"),
        Map.entry("25 Move Statements into Function", "MessagingForkSliceTest.java"),
        Map.entry("26 Move Statements to Callers", "MessagingForkSliceTest.java"),
        Map.entry("49 Replace Inline Code", "MessagingForkSliceTest.java"),
        Map.entry("5 Combine Functions into Class", "CollectionPipelineForkSliceTest.java"),
        Map.entry("48 Replace Function with Command", "MapReduceForkSliceTest.java"),
        Map.entry("64 Split Phase", "MapReduceForkSliceTest.java"),
        Map.entry("58 Replace Temp with Query", "MapReduceForkSliceTest.java")));

    /**
     * Whether some {@code @DisplayName} in this source names the given row NUMBER.
     *
     * <p>An {@code @DisplayName} belongs to a test method and disappears with it, which a
     * class javadoc does not — that difference is the whole point of looking here.</p>
     *
     * <p>Both {@code "row 26"} and {@code "rows 26 and 25"} count: rows 25 and 26 are
     * inverses and their one test runs them as a round trip, so its name says so. The check
     * is therefore for the word row (or rows) and the number as its own token, not for a
     * fixed phrase — a convention nobody has to remember is worth more than a tidier
     * regular expression that quietly excludes the honest case.</p>
     */
    private static boolean namesRowInADisplayName(String source, String number) {
        for (String line : source.split("\n", -1)) {
            if (line.contains("@DisplayName")
                    && line.matches(".*\\brows?\\b.*")
                    && line.matches(".*\\b" + number + "\\b.*")) {
                return true;
            }
        }
        return false;
    }

    @Test
    @DisplayName("this says exactly which of Stage 6's twelve rows are demonstrated on the fork")
    void theForkDemonstrationCountIsWhatIsWrittenDown() {
        Path root = Path.of(System.getProperty("user.dir")).resolve(TESTS);
        // Walk up: the runner's working directory is the dist, not the repository.
        for (Path at = Path.of("").toAbsolutePath(); at != null && !Files.isDirectory(root);
                at = at.getParent()) {
            root = at.resolve(TESTS);
        }
        assertTrue(Files.isDirectory(root),
            "PROOF OF LIFE: without the test sources this checks nothing. Looked for "
                + TESTS);

        List<String> wrong = new ArrayList<>();
        long claimed = 0;
        for (Map.Entry<String, String> row : ROWS.entrySet()) {
            if (row.getValue().isEmpty()) {
                continue;
            }
            claimed++;
            Path slice = root.resolve(row.getValue());
            if (!Files.isRegularFile(slice)) {
                wrong.add(row.getKey() + " claims " + row.getValue() + ", which is not there");
                continue;
            }
            // AND THAT A TEST IN IT IS ABOUT THIS ROW. Existence alone was all this checked
            // until a C6 audit named it: six slices are shared by two to four rows each, so
            // one could lose a row's method and stay green while claiming it demonstrated.
            //
            // THE FIRST FIX WAS VACUOUS and the next audit caught that too — it searched the
            // WHOLE FILE, and every slice names its rows in the class javadoc as well, so
            // deleting the test method still left a hit. Exactly the row it was added to
            // protect, 36, was the one it could not protect. The needle must therefore sit
            // where only a TEST can put it: an @DisplayName line.
            String number = row.getKey().split(" ")[0];
            try {
                if (!namesRowInADisplayName(Files.readString(slice), number)) {
                    wrong.add(row.getKey() + " claims " + row.getValue() + ", which exists"
                        + " but has no @DisplayName naming row " + number + " — a shared"
                        + " slice that lost this row's test reads exactly like this, and a"
                        + " class javadoc mentioning the row does not make it demonstrated");
                }
            } catch (java.io.IOException e) {
                wrong.add(row.getKey() + ": could not read " + row.getValue() + " — " + e);
            }
        }
        assertTrue(wrong.isEmpty(), String.join("\n  ", wrong));

        assertEquals(11, claimed,
            "ELEVEN rows of twelve are demonstrated on code we did not author. If that number"
                + " moved, this list is what says so — update it in the same commit as the"
                + " slice, or the count and the reality drift apart, which is the state a"
                + " C6 audit found and named.");
        assertEquals(12, ROWS.size(),
            "and all twelve rows are listed, so a row cannot be quietly dropped from the"
                + " question: " + ROWS.keySet());
    }
}
